arbolsaf/urls.py
from .views.species_views import *
from .views.variables_views import *
from .views.variable_type_views import *
from .views.reference_views import *
from .views.cross_table_views import *
from .views.tool_views import *
from .views.homepage_views import *
from .views.synonymous_views import sinonimo_delete, create_sinonimo, Synonymous2MCreateView
from django.urls import path 

app_name = 'arbolsaf'

urlpatterns = [
    path('principal', Homepage.as_view(),name='homepage'),
    path('especie/listado', SpeciesListView.as_view(),name='species_list'),
    path('especie/listado/json/', species_list_json ,name='species_list_json'),
    
    path('especie/detalles/<str:pk>', SpeciesDetailView.as_view(),name='species_detail'),
    path('especie/crear', SpeciesCreateView.as_view(),name='species_create'),
    path('especie/modificar/<str:pk>', SpeciesUpdateView.as_view(), name='species_update'),
    path('especie/eliminar', species_delete, name='species_delete'),
    path('especie/actualizar-herramienta/', UpdateToolValuesView.as_view(), name='species_update_tool_fields'),
    
    
    path('especie/<int:pk>/variable', create_variable_o2m, name='species_create_variable'),
    path('especie/<int:pk>/variable/diligenciar/<int:tipo>/', create_variable_o2m, name='species_diligenciar_variable'),
    
    #path('especie/<int:pk>/variable', VariableO2MCreateView.as_view(), name='species_create_variable'),
    #path('especie/<int:pk>/variable/diligenciar/<int:tipo>/', VariableO2MCreateView.as_view(), name='species_diligenciar_variable'),

    path('especie/variable/modificar/<str:pk>', VariableO2MUpdateView.as_view(), name='species_update_variable'),
    path('especie/variable/detalles/<str:pk>', Variable2MDetailView.as_view(),name='species_detail_variable'),
    path('variable/tipo', variable_tipo_get, name='variable_tipo'),
    path('variable/eliminar', variable_delete, name='variable_delete'),
    path('variable/opciones/', variable_get_opciones, name='variable_get_opciones'),
    path('especie/<int:pk>/sinonimo', Synonymous2MCreateView.as_view(), name='species_create_synonymous'),
    path('sinonimo/eliminar', sinonimo_delete, name='sinonimo_delete'),
    path('sinonimo/crear', create_sinonimo, name='sinonimo_create'),

    path('tipos_variable/listado', VariableTypeListView.as_view(),name='variable_type_list'),
    path('tipos_variable/detalles/<str:pk>', VariableTypeDetailView.as_view(),name='variable_type_detail'),
    path('tipos_variable/crear', VariableTypeCreateView.as_view(),name='variable_type_create'),
    path('tipos_variable/modificar/<str:pk>', VariableTypeUpdateView.as_view(), name='variable_type_update'),
    path('tipos_variable/eliminar', variable_type_delete, name='variable_type_delete'),


    path('referencia/listado', ReferenceListView.as_view(),name='reference_list'),
    path('referencia/detalles/<str:pk>', ReferenceDetailView.as_view(),name='reference_detail'),
    path('referencia/crear', ReferenceCreateView.as_view(),name='reference_create'),
    path('referencia/modificar/<str:pk>', ReferenceUpdateView.as_view(), name='reference_update'),
    path('referencia/eliminar', reference_delete, name='reference_delete'),

    path('tabla_cruzada/listado', CrossTableListView.as_view(), name='cross_table_list'),
    path('tabla_cruzada/exportar', ExportCsvView.as_view(), name='cross_table_export'),


    path('variable-especie/listado', VariableSpeciesListView.as_view(), name='variable_species_list'),


    path('variable-especie/detalles/<str:pk>', VariableSpeciesDetailView.as_view(),name='variable_species_detail'),
    path('tabla_cruzada/detalles/<str:pk>', CrossTableDetailView.as_view(),name='cross_table_detail'),
    

    
    path('variable-especie/crear', create_variable_specie, name='variable_species_create'),
    path('variable-especie/modificar/<str:pk>', VariableSpeciesUpdateView.as_view(),name='variable_species_update'),

    path('herramienta/intro/', IntroToolView.as_view(), name='tool_part0'),
    path('herramienta/', ToolView.as_view(), name='tool_part1'),

    #path('herramienta/pdf/', ToolPDFView.as_view(), name='tool_pdf'),
    path('herramienta/pdf/', tool_print_pdf_view, name='tool_pdf'),
    path('acerca-de/', AboutToolView.as_view(), name='about_page'),
    
    path('species/activar/<str:pk>/', SpeciesActivateInToolView.as_view(), name='species_activate'),
    path('species/desactivar/<str:pk>/', SpeciesDeactivateInToolView.as_view(), name='species_deactivate'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login /
    path('arbolsaf/', include('arbolsaf.urls', namespace="arbolsaf")), 
    path("", include("apps.home.urls"))             # UI Kits Html files
]

handler404 = 'core.error_views.render_404_view'
handler500 = 'core.error_views.render_500_view'
handler403 = 'core.error_views.render_403_view'
handler400 = 'core.error_views.render_400_view'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_url = '/arbolsaf/especie/listado'  # Removes the 'View Site' link

arbolsaf/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from computedfields.models import ComputedFieldsModel, computed, compute
import urllib.parse
from django.core.cache import cache
from ckeditor.fields import RichTextField

class BasicAuditModel(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, 
                related_name="+",
                verbose_name=_("Creado por"), 
                null=True,
                blank=False,
                on_delete=models.SET_NULL)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, 
                    related_name="+",
                    verbose_name=_("Modificado por"), 
                    null=True,
                    blank=False,
                    on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Fecha creado"))
    modified = models.DateTimeField(auto_now=True, verbose_name=_("Fecha modificado"))
    #active = models.BooleanField(default=True, verbose_name=_("Activo"))

    class Meta:
        abstract = True

class SynonymousModel(BasicAuditModel):
    

    sinonimo = models.CharField(_("sinónimo"), max_length=255)
    especie = models.ForeignKey("arbolsaf.SpeciesModel", verbose_name=_("Especie"), 
                    related_name="sinonimos", on_delete=models.CASCADE)
    def __str__(self):
        return self.sinonimo

    class Meta:
        db_table = 'arbolsaf_synonymous'
        managed = True
        ordering = ["sinonimo"]
        verbose_name = 'Sinónimo'
        verbose_name_plural = 'Sinónimo'

class FamilyModel(BasicAuditModel):

    familia = models.CharField(_("familia"), max_length=50)
    def __str__(self):
        return self.familia

    class Meta:
        db_table = 'arbolsaf_family'
        managed = True
        ordering = ["familia"]
        verbose_name = 'Familia'
        verbose_name_plural = 'Familias'

class GenderModel(BasicAuditModel):

    genero = models.CharField(_("género"), max_length=50)
    
    def __str__(self):
        return self.genero

    class Meta:
        db_table = 'arbolsaf_gender'
        managed = True
        ordering = ["genero"]
        verbose_name = 'Género'
        verbose_name_plural = 'Género'

class ReferenceModel(BasicAuditModel):

    fuente_final = models.CharField(_("Cita"), max_length=255)
    cod_cita = models.CharField(_("código cita"), max_length=50, unique=True)
    referencia = models.TextField(_("Fuente"), blank=True, null=True)

    def __str__(self):
        return self.fuente_final

    class Meta:
        db_table = 'arbolsaf_reference'
        managed = True
        ordering = ["fuente_final"]
        verbose_name = 'Referencia'
        verbose_name_plural = 'Referencias'

class MeasureUnitTypeModel(BasicAuditModel):

    abreviatura = models.CharField(_("abreviatura"), max_length=50)
    nombre = models.CharField(_("nombre"), max_length=50, blank=True, null=True)

    

    def __str__(self):
        return self.abreviatura

    class Meta:
        db_table = 'arbolsaf_measure_unit_type'
        managed = True
        ordering = ["abreviatura"]
        verbose_name = 'Tipo unidad de medidas'
        verbose_name_plural = 'Tipos unidad de medidas'

class FunctiomModel(BasicAuditModel):


    nombre = models.CharField(_("nombre"), max_length=50)

    

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'arbolsaf_function'
        managed = True
        verbose_name = 'Función'
        verbose_name_plural = 'Funciones'


class VariableTypeFamilyModel(BasicAuditModel):

    nombre = models.CharField(_("nombre"), max_length=50)
    descripcion = models.TextField(_("descripción"), blank=True, null=True)
    
    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'arbolsaf_variable_type_family'
        managed = True
        ordering = ["nombre"]
        verbose_name = 'Grupo de variable'
        verbose_name_plural = 'Grupos de variables'

class VariableTypeModel(BasicAuditModel):

    TYPE_CHOICES = (
        ("boolean", "Boolean"),
        ("cualitativo", "Cualitativo"),
        ("numerico", "Numérico"),
        ("rango", "Rango"),
        ("texto", "Texto"),
    )
    seleccion_multiple = models.BooleanField(_("Es selección múltiple? (Aplicable solo a variables cualitativas)"), default=False)

    cod_var = models.CharField(_("código variable"), max_length=50)
    tipo_variables = models.CharField(_("tipo variable"), 
                    choices=TYPE_CHOICES, max_length=50, blank=True, null=True)
    
    unidad_medida =  models.ForeignKey("arbolsaf.MeasureUnitTypeModel", verbose_name=_("Unidad de medida"), 
                on_delete=models.SET_NULL, blank=True, null=True)
    
    familia =  models.ForeignKey("arbolsaf.VariableTypeFamilyModel", verbose_name=_("Grupo"),
                on_delete=models.SET_NULL, blank=True, null=True)

                
    variable = models.CharField(_("variable"), max_length=255)
    niveles_categoricos = models.TextField(_("Niveles categóricos"))
    descripcion = models.TextField(_("descripción"), blank=True, null=True)    

    min = models.FloatField(_("Valor mínimo"), blank=True, null=True)
    max = models.FloatField(_("Valor máximo"), blank=True, null=True)

    uso_herramienta = models.BooleanField(_("Utilizada en herramienta"), default=False)

    def __str__(self):
        return f"{self.variable} ({self.cod_var})"

    class Meta:
        db_table = 'arbolsaf_variable_type'
        ordering = ["variable"]
        managed = True
        verbose_name = 'Tipo de variable'
        verbose_name_plural = 'Tipos de variable'


class VariableTypeOption(models.Model):

    def __str__(self):
        return self.nombre

    tipo_variable = models.ForeignKey("arbolsaf.VariableTypeModel", verbose_name=_("Tipo de Variable"), 
                on_delete=models.RESTRICT) 
    
    nombre = models.CharField(_("Nombre"), max_length=50)

    class Meta:
        db_table = 'arbolsaf_variable_type_option'
        managed = True
        verbose_name = 'Opción Tipo Variable'
        verbose_name_plural = 'Opciones Tipo Variable'

class VariableModel(BasicAuditModel):


    referencia = models.ForeignKey("arbolsaf.ReferenceModel", verbose_name=_("Fuente"), 
                        on_delete=models.RESTRICT,  blank=True, null=True)
    referencia_2 = models.ForeignKey("arbolsaf.ReferenceModel", verbose_name=_("Repetir fuente"), 
                        on_delete=models.RESTRICT,  blank=True, null=True, related_name="+")
    tipo_variable = models.ForeignKey("arbolsaf.VariableTypeModel", verbose_name=_("Variable"), 
                    on_delete=models.RESTRICT)                    
    #nombre = models.CharField(_("nombre"), max_length=255)

    valor_numerico = models.FloatField(_("Valor numérico"), blank=True, null=True)
    rango_superior = models.FloatField(_("rango superior"), blank=True, null=True)
    rango_inferior = models.FloatField(_("rango inferior"), blank=True, null=True)
    valor_texto = models.CharField(_("Valor texto"), max_length=255, blank=True, null=True)
    valor_boolean = models.BooleanField(_("Verdadero?"), default=False, null=True)

    valor_general = models.CharField(_("Valor general"), max_length=255, blank=True, null=True)
    #valor_cualitativo = models.ForeignKey("arbolsaf.VariableTypeOption", verbose_name=_("Valor cualitativo"), 
    #                on_delete=models.RESTRICT, blank=True, null=True) 
    valores_cualitativos =   models.ManyToManyField("arbolsaf.VariableTypeOption", verbose_name=_("Valores cualitativos"), blank=True, null=True)
    #TODO averiguar si categoria puede ser una llave foranea

    #categoria = models.CharField(_("categoria"), max_length=50, blank=True, null=True)
    
    especie = models.ForeignKey("arbolsaf.SpeciesModel", related_name="variables", verbose_name=_("Especie"), on_delete=models.CASCADE)

    chequeo = models.BooleanField(_("Chequeada?"), default=False) 
    
    def __str__(self):
        return "{} - Especie: {}".format(self.tipo_variable, self.especie)
    
    @property
    def get_valor_general(self):
        valor=""

        if self.tipo_variable.tipo_variables == 'cualitativo':
            nombres=  [valor.nombre for valor in self.valores_cualitativos.all()]
            valor = ','.join(nombres)
        elif self.tipo_variable.tipo_variables == 'numerico': 
            valor = f"{self.rango_inferior};{self.rango_superior}"
        elif self.tipo_variable.tipo_variables == 'texto': 
            valor = self.valor_texto
        elif self.tipo_variable.tipo_variables == 'rango': 
            valor = f"{self.rango_inferior};{self.rango_superior}"
        elif self.tipo_variable.tipo_variables == 'boolean': 
            valor = "SI" if self.valor_boolean else "NO"
        else:
            valor = self.valor_general or ""

        return valor

    class Meta:
        db_table = 'arbolsaf_variable'
        managed = True
        verbose_name = 'Variable'
        verbose_name_plural = 'Variable'


class DistributionMenaceModel(BasicAuditModel):


    nombre = models.CharField(_("nombre"), max_length=50)

    tipo_variable = models.ForeignKey("arbolsaf.VariableTypeModel", verbose_name=_("Variable"), on_delete=models.RESTRICT)

    especie = models.ForeignKey("arbolsaf.SpeciesModel", verbose_name=_(""), on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'arbolsaf_distribution_menace'
        managed = True
        verbose_name = 'Amenaza distribución'
        verbose_name_plural = 'Amenazas distribución'

class SpeciesModel(BasicAuditModel, ComputedFieldsModel):


    habilitada_herramienta = models.BooleanField(_("Habilitada en herramienta"), default=False)

    VALUES_CHOICES = (
        ("ninguno", "Ninguno"),
        ("bajo", "Bajo"),
        ("medio", "Medio"),
        ("alto", "Alto"),
    )
        

arbolsaf/views/error_views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render



class TempateView404(TemplateView):
    template_name = 'apps/templates/home/page-404.html.html'



def render_404_view(request):
    context = {}
    return render(request, 'apps/templates/home/page-404.html.html', context)

arbolsaf/views/homepage_views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class Homepage(TemplateView):
    template_name = "arbolsaf/homepage.html"

arbolsaf/templates/arbolsaf/variable_type/variable_type_detail.html
{% extends 'layouts/base.html' %}
{% load user_has_group %}
{% block title %} Formulario Variable {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}


<style type="text/css">



</style>
{% endblock stylesheets %}

{% block body_class %} g-sidenav-show bg-gray-100 {% endblock %}

{% block content %}

  <div class="container-fluid py-4">

    <div class="row">
      <div class="col-lg-12 col-12 mx-auto">
        
        <div class="card card-body mt-4">
          <!--h6 class="mb-0">New Project</h6>
          <p class="text-sm mb-0">Create new project</p-->
            <div class="row">
              <div class="col-6">
               <h3> Detalles: <span>'{% firstof variable.variable|default_if_none:"-"|capfirst %}' </span></h3>           
              </div>
              <div class="col-6">
                  <div class="d-flex justify-content-end">
                      <a href="{% url 'arbolsaf:variable_type_list' %}"
                      class="btn btn-secondary btn-large btn-sm m-b-xm mx-1"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;Atrás</a>
                      {% if request.user|has_group:"editor" or request.user.is_superuser %} 
                  <a href="{% url 'arbolsaf:variable_type_create' %}"
                      class="btn btn-primary btn-large btn-sm m-b-xm mx-1"><i class="fa fa-plus"></i>&nbsp;&nbsp;Crear</a>
                  
                 
                  <a href="{% url 'arbolsaf:variable_type_update' variable.id %}"
                      class="btn btn-info btn-large btn-sm m-b-xm mx-1"><i class="fa fa-edit"></i>&nbsp;&nbsp;Editar</a>
                  <!--a class="btn btn-danger btn-large btn-sm m-b-xm"><i class="fa fa-edit"></i>&nbsp;&nbsp;Eliminar</a-->
                  <button class="btn btn-danger btn-large btn-sm m-b-xm mx-1"
                          id="eliminarB"
                          data-bs-toggle="modal"
                          data-bs-target="#deleteModal"
                          value="{{ variable.id }} ">
                    <i class="far fa-trash-alt me-2" aria-hidden="true"></i>&nbsp;&nbsp;Eliminar
                  </button>
                  {% endif %}
           
                </div>
              </div>

            </div>

          <hr class="horizontal dark my-3">


          <div class="row mb-2">
            <div class="col-3">
              <div class="form-group">
                <h6>Código variable </h6>
                <span class="mr-2">{% firstof variable.cod_var|default_if_none:"-" %}</span>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <h6>Variable </h6>
                <span class="mr-2">{% firstof variable.variable|default_if_none:"-"|capfirst %}</span>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <h6>Unidad de medida </h6>
                <span class="mr-2">{% firstof variable.unidad_medida|default_if_none:"-" %}</span>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <h6>Tipo de Variable </h6>
                <span class="mr-2">{% firstof variable.get_tipo_variables_display|default_if_none:"-"|capfirst %}</span>
              </div>
            </div>
          
          </div>

          <div class="row mb-2">
            <div class="col-3">
              <div class="form-group">
                <h6>Grupo </h6>
                <span class="mr-2">{% firstof variable.familia|default_if_none:"-"|capfirst %}</span>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <h6>Min </h6>
                <span class="mr-2">{% firstof variable.min|default_if_none:"-" %}</span>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <h6>Max </h6>
                <span class="mr-2">{% firstof variable.max|default_if_none:"-" %}</span>
              </div>
            </div>

            <div class="col-3">
              <div class="form-group">
                <div class="form-group">
                  <h6>Utilizada en la herramienta</h6>
                  <div class="mr-2">
                    {{ variable.uso_herramienta|yesno:_("SÍ,NO") }}
                  </div>
                </div>
              </div>
            </div>
            <!--div class="col-3">
              <div class="form-group">
                <h6>Tipo Variable </h6>
                <spam class="mr-2">{% firstof variable.get_tipo_variables_display|default_if_none:"-" %}</span>
              </div>
            </div-->
          
          </div>

          <div class="row mb-2">
            <div class="col-3">
              <div class="form-group">
                <h5>Niveles categoricos </h5>
                <span class="mr-2">{% firstof variable.niveles_categoricos|default_if_none:"-" %}</span>
              </div>
            </div>
          </div>

          <div class="row mb-2">
            <div class="col-12">
              <div class="form-group">
                <h5>Descripción </h5>
                <span class="mr-2">{% firstof variable.descripcion|default_if_none:"-" %}</span>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
        <div class="modal fade"
            id="deleteModal"
            tabindex="-1"
            role="dialog"
            aria-labelledby="exampleModalLabel"
            aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Eliminar</h5>
              <button type="button"
                      class="btn-close text-dark"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                      id="elim">
                <!--span aria-hidden="true">&times;</span-->
              </button>
            </div>
            <div class="modal-body">
              <p class="text-sm mb-0 text-capitalize font-weight-bold">Está seguro que desea eliminarel tipo de variable?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn bg-success" data-bs-dismiss="modal">Cerrar</button>
              <button type="button" class="btn bg-danger text-white" id="aceptar">Aceptar</button>
            </div>
          </div>
        </div>
        </div>
    {% include "includes/footer.html" %}
    
  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %} 

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<script type="text/javascript">
document.getElementById("aceptar").addEventListener('click', function(){

  console.log('ACEPTAR');
  var valor = document.getElementById('eliminarB').value;

  var request = $.ajax({
      type: "GET",
      url: "/arbolsaf/tipos_variable/eliminar",
      data: {
          "id": valor
      },
      success: function (response) {
          console.log(response)
          $("#deleteModal").modal('hide');
          $(location).attr('href', "{% url 'arbolsaf:variable_type_list'%}");

      },
      error: function (response, e) {
          console.log(response);
          
          $("#deleteVariable").modal('hide');
          if (response.responseJSON.mensaje =='restricted'){
               alert(response.responseJSON.error);
          }
          else{
             alert('Ha ocurrido un error al eliminar, Contacte al Administrador');
          }
          
          
      }
  });

});   
</script>
{% endblock javascripts %}

arbolsaf/templates/arbolsaf/variable_type/variable_type_form.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}
  Formulario tipo variable
{% endblock title %}
<!-- Specific CSS goes HERE -->
{% block stylesheets %}
{% endblock stylesheets %}
{% block body_class %}g-sidenav-show bg-gray-100{% endblock %}
{% block content %}
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-lg-12 col-12 mx-auto">
        <form enctype="multipart/form-data" method="post" name="theForm">
          {% csrf_token %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger text-white">
                  <strong>{{ error|escape }}</strong>
                  {{ field.label|capfirst }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger text-white">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endif %}
          <div class="card card-body mt-4">
            <!--h6 class="mb-0">New Project</h6>
          <p class="text-sm mb-0">Create new project</p-->
            <div class="row">
              <div class="col-7">
                {% if not form.instance.id %}
                  <h3>Nuevo tipo variable</h3>
                {% else %}
                  <h3>
                    Actualizar tipo variable:  <span>'{% firstof variable.variable|default_if_none:"-"|capfirst %}'</span>
                  </h3>
                {% endif %}
              </div>
              <div class="col-5">
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary btn-large btn-sm m-b-xm mx-1">
                    <i class="fa fa-save"></i>&nbsp;&nbsp;Guardar
                  </button>
                  {% if not form.instance.id %}
                  <a href="{% url 'arbolsaf:variable_type_list' %}"
                     class="btn btn-danger btn-large btn-sm m-b-xm mx-1"><i class="fa fa-undo"></i>&nbsp;&nbsp;Cancelar</a>
                {% else %}
                  <a href="{% url 'arbolsaf:variable_type_detail' form.instance.id %}"
                     class="btn btn-danger btn-large btn-sm m-b-xm mx-1"><i class="fa fa-undo"></i>&nbsp;&nbsp;Cancelar</a>
                {% endif %}
                </div>
              </div>
            </div>
            <hr class="horizontal dark my-3">
            
            <div class="row mt-4 mb-2">
              <div class="col-3">
                <div class="form-group">
                  <h6>
                    {{ form.cod_var.label }}
                    {% if form.cod_var.required %}<span>*</span>{% endif %}
                  </h6>
                  {{ form.cod_var }}
                </div>
              </div>
              <div class="col-3">
                <div class="form-group">
                  <h6>
                    {{ form.variable.label }}
                    {% if form.variable.field.required %}<span>*</span>{% endif %}
                  </h6>
                  {{ form.variable }}
                </div>
              </div>
              <div class="col-3">
                <div class="form-group">
                  <h6>
                    {{ form.unidad_medida.label }}
                    {% if form.unidad_medida.field.required %}<span>*</span>{% endif %}
                  </h6>
                  {{ form.unidad_medida }}
                </div>
              </div>
              <div class="col-3">
                <div class="form-group">
                  <h6>
                    {{ form.tipo_variables.label }}
                    {% if form.tipo_variables.field.required %}<span>*</span>{% endif %}
                  </h6>
                  {{ form.tipo_variables }}
                </div>
              </div>
            </div>

            <div class="row mb-2">
              <div class="col-3">
                <div class="form-group">
                  <h6>
                    {{ form.familia.label }}
                    {% if form.familia.required %}<span>*</span>{% endif %}
                  </h6>
                  {{ form.familia }}
                </div>
              </div>
              <div class="col-3">
                <div class="form-group">
                  <h6>
                    {{ form.min.label }}
                    {% if form.min.field.required %}<span>*</span>{% endif %}
                  </h6>
                  {{ form.min }}
                </div>
              </div>
              <div class="col-3">
                <div class="form-group">
                  <h6>
                    {{ form.max.label }}
                    {% if form.max.field.required %}<span>*</span>{% endif %}
                  </h6>
                  {{ form.max }}
                </div>
              </div>
              <!--div class="col-3">
                <div class="form-group">
                  <h6>
                    {{ form.uso_herramienta.label }}
                    {% if form.uso_herramienta.field.required %}<span>*</span>{% endif %}
                  </h6>
                  <div class="form-check">{{ form.uso_herramienta }}</div>
                </div>
              </div-->
            </div>

            <div class="row mb-2">
              <div class="col-12">
                <div class="form-group">
                  <h5>
                    {{ form.niveles_categoricos.label }}
                    {% if form.niveles_categoricos.required %}<span>*</span>{% endif %}
                  </h5>
                  {{ form.niveles_categoricos }}
                </div>
              </div>

            </div>

            <div class="row mb-2">
              <div class="col-12">
                <div class="form-group">
                  <h5>
                    {{ form.descripcion.label }}
                    {% if form.descripcion.required %}<span>*</span>{% endif %}
                  </h5>
                  {{ form.descripcion }}
                </div>
              </div>

            </div>

          </div>
        </form>
      </div>

      
    </div>
    {% include "includes/footer.html" %}
  </div>
{% endblock content %}
<!-- Specific JS goes HERE -->
{% block javascripts %}
  <script src="https://code.jquery.com/jquery-3.5.0.js"></script>



{% endblock javascripts %}