arbolsaf/urls.py
from .views.species_views import *
from .views.variables_views import *
from .views.variable_type_views import *
from .views.reference_views import *
from .views.cross_table_views import *
from .views.tool_views import *
from .views.homepage_views import *
from .views.synonymous_views import sinonimo_delete, create_sinonimo, Synonymous2MCreateView
from django.urls import path 

app_name = 'arbolsaf'

urlpatterns = [
    path('principal', Homepage.as_view(),name='homepage'),
    path('especie/listado', SpeciesListView.as_view(),name='species_list'),
    path('especie/listado/json/', species_list_json ,name='species_list_json'),
    
    path('especie/detalles/<str:pk>', SpeciesDetailView.as_view(),name='species_detail'),
    path('especie/crear', SpeciesCreateView.as_view(),name='species_create'),
    path('especie/modificar/<str:pk>', SpeciesUpdateView.as_view(), name='species_update'),
    path('especie/eliminar', species_delete, name='species_delete'),
    path('especie/actualizar-herramienta/', UpdateToolValuesView.as_view(), name='species_update_tool_fields'),
    
    
    path('especie/<int:pk>/variable', create_variable_o2m, name='species_create_variable'),
    path('especie/<int:pk>/variable/diligenciar/<int:tipo>/', create_variable_o2m, name='species_diligenciar_variable'),
    
    #path('especie/<int:pk>/variable', VariableO2MCreateView.as_view(), name='species_create_variable'),
    #path('especie/<int:pk>/variable/diligenciar/<int:tipo>/', VariableO2MCreateView.as_view(), name='species_diligenciar_variable'),

    path('especie/variable/modificar/<str:pk>', VariableO2MUpdateView.as_view(), name='species_update_variable'),
    path('especie/variable/detalles/<str:pk>', Variable2MDetailView.as_view(),name='species_detail_variable'),
    path('variable/tipo', variable_tipo_get, name='variable_tipo'),
    path('variable/eliminar', variable_delete, name='variable_delete'),
    path('variable/opciones/', variable_get_opciones, name='variable_get_opciones'),
    path('especie/<int:pk>/sinonimo', Synonymous2MCreateView.as_view(), name='species_create_synonymous'),
    path('sinonimo/eliminar', sinonimo_delete, name='sinonimo_delete'),
    path('sinonimo/crear', create_sinonimo, name='sinonimo_create'),

    path('tipos_variable/listado', VariableTypeListView.as_view(),name='variable_type_list'),
    path('tipos_variable/detalles/<str:pk>', VariableTypeDetailView.as_view(),name='variable_type_detail'),
    path('tipos_variable/crear', VariableTypeCreateView.as_view(),name='variable_type_create'),
    path('tipos_variable/modificar/<str:pk>', VariableTypeUpdateView.as_view(), name='variable_type_update'),
    path('tipos_variable/eliminar', variable_type_delete, name='variable_type_delete'),


    path('referencia/listado', ReferenceListView.as_view(),name='reference_list'),
    path('referencia/detalles/<str:pk>', ReferenceDetailView.as_view(),name='reference_detail'),
    path('referencia/crear', ReferenceCreateView.as_view(),name='reference_create'),
    path('referencia/modificar/<str:pk>', ReferenceUpdateView.as_view(), name='reference_update'),
    path('referencia/eliminar', reference_delete, name='reference_delete'),

    path('tabla_cruzada/listado', CrossTableListView.as_view(), name='cross_table_list'),
    path('tabla_cruzada/exportar', ExportCsvView.as_view(), name='cross_table_export'),


    path('variable-especie/listado', VariableSpeciesListView.as_view(), name='variable_species_list'),


    path('variable-especie/detalles/<str:pk>', VariableSpeciesDetailView.as_view(),name='variable_species_detail'),
    path('tabla_cruzada/detalles/<str:pk>', CrossTableDetailView.as_view(),name='cross_table_detail'),
    

    
    path('variable-especie/crear', create_variable_specie, name='variable_species_create'),
    path('variable-especie/modificar/<str:pk>', VariableSpeciesUpdateView.as_view(),name='variable_species_update'),

    path('herramienta/intro/', IntroToolView.as_view(), name='tool_part0'),
    path('herramienta/', ToolView.as_view(), name='tool_part1'),

    #path('herramienta/pdf/', ToolPDFView.as_view(), name='tool_pdf'),
    path('herramienta/pdf/', tool_print_pdf_view, name='tool_pdf'),
    path('acerca-de/', AboutToolView.as_view(), name='about_page'),
    
    path('species/activar/<str:pk>/', SpeciesActivateInToolView.as_view(), name='species_activate'),
    path('species/desactivar/<str:pk>/', SpeciesDeactivateInToolView.as_view(), name='species_deactivate'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login /
    path('arbolsaf/', include('arbolsaf.urls', namespace="arbolsaf")), 
    path("", include("apps.home.urls"))             # UI Kits Html files
]

handler404 = 'core.error_views.render_404_view'
handler500 = 'core.error_views.render_500_view'
handler403 = 'core.error_views.render_403_view'
handler400 = 'core.error_views.render_400_view'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_url = '/arbolsaf/especie/listado'  # Removes the 'View Site' link

arbolsaf/views/cross_table_views.py
import csv

from django.http import HttpResponse
from django.views.generic import ListView, View, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import SpeciesModel, VariableTypeModel, ReferenceModel, VariableModel
from ..forms import VariableSpeciesForm
from django.urls import reverse_lazy
from ..permissions import GroupRequiredMixin, group_required


class CrossTableListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    model = SpeciesModel
    group_required = [u'visualizador', u'editor']
    template_name = 'arbolsaf/cross_table/cross_table_list.html'
    context_object_name = 'cross_table'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super(CrossTableListView, self).get_context_data(*args, **kwargs)

        context['segment'] = ['arbolsaf', 'cross_table']
        context['active_menu'] = 'arbolsaf'

        context['nombre_comun'] = self.request.GET.get('nombre_comun', '')
        context['value_nombre_comun'] = self.request.GET.get('nombre_comun', '')
        context['value_nombre_cientifico'] = self.request.GET.get('nombre_cientifico', '')
        context['value_tipo_variable'] = self.request.GET.get('tipo_variable', '')
        context['value_referencia'] = self.request.GET.get('referencia', '')
        context['value_cod_var'] = self.request.GET.get('cod_var', '')
        context['value_cod_esp'] = self.request.GET.get('cod_esp', '')

        
        
        filtrado = context['nombre_comun'] + context['value_nombre_comun'] + context['value_nombre_cientifico'] + \
                   context['value_tipo_variable'] + context['value_referencia'] +  context['value_cod_var'] + context['value_cod_esp']

        print(len(filtrado))

        context['ordenar_por'] = self.request.GET.get('ordenar_por', 'nombre_comun')

        context['has_filters'] = False

        if len(filtrado) > 0:
            context['has_filters'] = True

        especies = SpeciesModel.objects.all()

        #nombre_comun_values = list()
        #for especie in especies.order_by('nombre_comun'):
        #    nombre_comun_values.append(f"{especie.nombre_comun} ({especie.cod_esp})")

        #context['nombre_comun_values'] = nombre_comun_values

        nombre_cientifico_values = list()
        for especie in especies.order_by('nombre_cientifico'):
            nombre_cientifico_values.append({"nombre_cientifico":especie.nombre_cientifico,"cod_esp":especie.cod_esp})

        context['nombre_cientifico_values'] = nombre_cientifico_values

        
        variables = VariableTypeModel.objects.order_by('variable')
        context['variables'] = variables

        referencias = ReferenceModel.objects.order_by('fuente_final')
        context['referencias'] = referencias

        if context['is_paginated']:
            list_pages = []

            first_range = self.request.GET.get('page', '1')
            actual_rows = round(int(first_range) * self.paginate_by)
            total_rows = len(CrossTableListView.get_queryset(self))

            context['count_actual_rows'] = total_rows if actual_rows > total_rows else actual_rows
            context['total_rows'] = total_rows

            if 'nombre_cientifico' not in self.request.GET:
                for i in range(context['page_obj'].number, context['page_obj'].number + 5):
                    if i <= context['page_obj'].paginator.num_pages:
                        list_pages.append(i)
            else:

                if len(CrossTableListView.get_queryset(self)) % self.paginate_by == 0:
                    paginated = int(len(CrossTableListView.get_queryset(self)) / self.paginate_by)
                else:
                    paginated = int(len(CrossTableListView.get_queryset(self)) / self.paginate_by) + 1

                if paginated > 1:
                    for i in range(int(first_range), int(first_range) + 5):
                        if i <= paginated:
                            list_pages.append(i)

                    context['total_pages'] = paginated
                    context['has_more_pages'] = True if int(first_range) < paginated else False
                    context['next_page'] = int(first_range) + 1 if int(first_range) < paginated else '0'
                    context['has_previous_pages'] = True if int(first_range) > 1 else False
                    context['previous_page'] = int(first_range) - 1 if int(first_range) > 1 else '0'
                    context['actual_page'] = int(first_range)

            context['paginator_rows'] = list_pages

        return context

    def get_queryset(self):
        query = {
            #'nombre_comun': self.request.GET.get('nombre_comun', None),
            'cod_var': self.request.GET.get('cod_var', None),
            'cod_esp': self.request.GET.get('cod_esp', None),
            'nombre_cientifico': self.request.GET.get('nombre_cientifico', None),
            'tipo_variable': self.request.GET.get('tipo_variable', None),
            'referencia': self.request.GET.get('referencia', None),
        }
        tipos_de_orden = {
            'nombre_comun': 'especie__nombre_comun',
            'nombre_comun_dec': '-especie__nombre_comun',
            'nombre_cientifico': 'especie__nombre_cientifico',
            'nombre_cientifico_dec': '-especie__nombre_cientifico',
            'tipo_variable': 'tipo_variable__tipo_variables',
            'tipo_variable_dec': '-tipo_variable__tipo_variables',
            'referencia': 'referencia__fuente_final',
            'referencia_dec': '-referencia__fuente_final',
            'valor': 'valor_general',
            'valor_dec': '-valor_general'

        }
        orden = self.request.GET.get('ordenar_por', 'nombre_comun')

        query_result = VariableModel.objects

        #if query['nombre_comun'] and query['nombre_comun'] != '':
        #    query_result = query_result.filter(especie__nombre_comun__icontains=query['nombre_comun'])
        if query['nombre_cientifico'] and query['nombre_cientifico'] != '':
            query_result = query_result.filter(especie__nombre_cientifico__icontains=query['nombre_cientifico'])
        
        if query['cod_var'] and query['cod_var'] != '':
            query_result = query_result.filter(tipo_variable__cod_var__iexact=query['cod_var'])
        if query['cod_esp'] and query['cod_esp'] != '':
            query_result = query_result.filter(especie__cod_esp__iexact=query['cod_esp'])

        if query['tipo_variable'] and query['tipo_variable'] != '':
            tipo_variable = VariableTypeModel.objects.get(pk=int(query['tipo_variable']))
            query_result = query_result.filter(tipo_variable=tipo_variable)

        if query['referencia'] and query['referencia'] != '':
            referencia = ReferenceModel.objects.get(pk=int(query['referencia']))
            query_result = query_result.filter(referencia=referencia)

        if orden in tipos_de_orden:
            query_result = query_result.order_by(tipos_de_orden[orden])
        else:
            query_result = query_result.order_by(tipos_de_orden['nombre_comun'])

        return query_result


class ExportCsvView(LoginRequiredMixin, GroupRequiredMixin, View):
    group_required = [u'visualizador', u'editor']

    def get(self, request):
        query = {
            'nombre_comun': self.request.GET.get('nombre_comun', None),
            'nombre_cientifico': self.request.GET.get('nombre_cientifico', None),
            'tipo_variable': self.request.GET.get('tipo_variable', None),
            'referencia': self.request.GET.get('referencia', None),
        }

        query_result = VariableModel.objects.order_by('especie__nombre_comun')

        if query['nombre_comun'] and query['nombre_comun'] != '':
            query_result = query_result.filter(especie__nombre_comun__icontains=query['nombre_comun'])
        if query['nombre_cientifico'] and query['nombre_cientifico'] != '':
            query_result = query_result.filter(especie__nombre_cientifico__icontains=query['nombre_cientifico'])

        if query['tipo_variable'] and query['tipo_variable'] != '':
            tipo_variable = VariableTypeModel.objects.get(pk=int(query['tipo_variable']))
            query_result = query_result.filter(tipo_variable=tipo_variable)

        if query['referencia'] and query['referencia'] != '':
            referencia = ReferenceModel.objects.get(pk=int(query['referencia']))
            query_result = query_result.filter(referencia=referencia)

        #response = HttpResponse('text/csv')
        #response['Content-Disposition'] = 'attachment; filename=tabla_cruzada.csv'

        response = HttpResponse(
            content_type="text/csv",
            headers={"Content-Disposition": 'attachment; filename="tabla_cruzada.csv"'},
            )
        
        writer = csv.writer(response)
        writer.writerow(['ID','Código especie','Nombre Común', 'Nombre Científico','Código Variable', 'Tipo de variable', 'Código referencia', 'Referencia', 'Valor'])

        for item in query_result:

            
            especie = item.especie
            valor=False
            if item.tipo_variable.tipo_variables == 'cualitativo':
                nombres=  [valor.nombre for valor in item.valores_cualitativos.all()]
                valor = ','.join(nombres)
            elif item.tipo_variable.tipo_variables == 'numerico': 
                valor = f"{item.rango_inferior};{item.rango_superior}"
            elif item.tipo_variable.tipo_variables == 'texto': 
                valor = item.valor_texto
            elif item.tipo_variable.tipo_variables == 'rango': 
                valor = f"{item.rango_inferior};{item.rango_superior}"
            elif item.tipo_variable.tipo_variables == 'boolean': 
                valor = "SI" if item.valor_boolean else "NO"
            else:
                valor = item.valor_general or ""
            
            if not valor or valor=='':
                valor = item.valor_general or ""

arbolsaf/views/error_views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render



class TempateView404(TemplateView):
    template_name = 'apps/templates/home/page-404.html.html'



def render_404_view(request):
    context = {}
    return render(request, 'apps/templates/home/page-404.html.html', context)

arbolsaf/views/homepage_views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class Homepage(TemplateView):
    template_name = "arbolsaf/homepage.html"

arbolsaf/templates/arbolsaf/homepage.html
{% extends 'layouts/base-fullscreen.html' %}
{% load static %}
{% block title %}
  Herramienta
{% endblock title %}
<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style type="text/css">

  .letra {
    font-size: 1.4rem;
    color: black !important;
  }

</style>

{% endblock stylesheets %}
{% block body_class %}error-page{% endblock %}
{% block content %}
  <!-- Navbar -->
  <nav class="card top-0 rounded-0">
    <div class="w-100 object-fit-cover">
      <a href="{% url 'arbolsaf:homepage' %}"><img src="/static/assets/img/herramienta/Cabecera_1_ÁrbolSAF.png"
           class="w-100"></a>
    </div>
  </nav>
  <!-- End Navbar -->
  <main class="main-content mt-2">
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-1">
        </div>
        <div class="col-10">
          <div class="card card-body p-5">
            <p class="text-left letra">
              ÁrbolSAF forma parte de un conjunto de soluciones digitales que CIFOR-ICRAF desarrolla para apoyar al codiseño informado de opciones agroforestales con múltiples objetivos y funciones. Consta de una plataforma de gestión de datos y de una herramienta interactiva.
            </p>
            <p class="text-left letra">
              La plataforma de gestión de datos alimenta la herramienta interactiva e incluye una lista de especies de árboles y palmeras, una lista de 163 variables o propiedades de esas especies relativas a copa, semillas, troncos, usos, y necesidades climáticas y de suelo, además del listado de fuentes de literatura revisada.
            </p>
            <p class="text-left letra">
              La herramienta guía y acompaña al técnico/agricultor/investigador a seleccionar las especies de árboles y palmeras más apropiadas tomando en cuenta los objetivos del agricultor, el contexto biofísico del área donde se intervendrá y los requerimientos de clima y suelo, y características morfológicas y funcionales de las especies. 
            </p>
            <p class="text-left letra">
              Siguiendo el enfoque de CIFOR-ICRAF de Opciones por Contexto aplicado a la agroforestería, ÁrbolSAF no pretende dar una receta, sino facilitar y hacer accesible la información necesaria para ayudar al usuario a tomar decisiones informadas sobre los árboles y palmeras que podrían ser parte de su opción agroforestal. 
            </p>
            <div></div>
            <div class="d-flex justify-content-center mt-5">
              <a href="{% url 'arbolsaf:about_page' %}" class="btn btn-large btn-lg m-b-xm mx-3 p-4" style="border-radius: 1rem; background-color: #806377; color: #f8f9fa;">
                {% comment %} &nbsp;&nbsp;<i class="fa fa-tools"></i> {% endcomment %}
                Acerca de 
              </a>
              {% if user.is_authenticated %}
              <a href="{% url 'arbolsaf:species_list' %}" class="btn btn-large btn-lg m-b-xm mx-3 p-4" style="border-radius: 1rem; background-color: #ee685f; color: #f8f9fa;">
                {% comment %} <i class="fa fa-cog"></i>&nbsp;&nbsp; {% endcomment %}
                Plataforma de gestión de datos
              </a>
              {% else %}
              <a href="{% url 'login' %}" class="btn btn-large btn-lg m-b-xm mx-3 p-4" style="border-radius: 1rem; background-color: #ee685f; color: #f8f9fa;">
                {% comment %} <i class="fa fa-cog"></i>&nbsp;&nbsp; {% endcomment %}
                Plataforma de gestión de datos
              </a>
              {% endif %}
              <a href="{% url 'arbolsaf:tool_part1' %}" class="btn btn-primary btn-large btn-lg m-b-xm mx-3 p-4" style="border-radius: 1rem;">
                {% comment %} &nbsp;&nbsp;<i class="fa fa-tools"></i> {% endcomment %}
                Herramienta
              </a>
            </div>
          </div>
        </div>
        <div class="col-1">
        </div>
      </div>
      {% comment %} {% include "includes/footer.html" %} {% endcomment %}
    </div>
  </main>
  {% include "includes/footer-tool.html" %}
  {#% include "includes/footer-auth.html" %#}
{% endblock content %}
<!-- Specific JS goes HERE -->
{% block javascripts %}
  <!--script src="/static/assets/js/plugins/datatables.js"></script-->
  <script src="{% static 'assets/js/tool_arbolsaf.js' %}"></script>
  <script src="/static/assets/js/plugins/multistep-form.js"></script>
  <script src="/static/assets/js/plugins/choices.min.js"></script>
  <script src="/static/assets/js/plugins/datatables.js"></script>
  {% comment %} <script>
      if (document.getElementById('table-conditions')) {
        const dataTableSearch = new simpleDatatables.DataTable("#table-conditions", {
          searchable: true,
          fixedHeight: false,
          perPage: 7
        });
  
        document.querySelectorAll(".export").forEach(function(el) {
          el.addEventListener("click", function(e) {
            var type = el.dataset.type;
  
            var data = {
              type: type,
              filename: "soft-ui-" + type,
            };
  
            if (type === "csv") {
              data.columnDelimiter = "|";
            }
  
            dataTableSearch.export(data);
          });
        });
      };
  </script> {% endcomment %}
  {% comment %} $(document).ready(function() {
      $('input').on( 'change', function() {
        if( $(this).is(':checked') ) {
            console.log('parentSel', $(this));  

            alert("El checkbox con valor " + $(this).val() + " ha sido seleccionado");
        } else {
            // Hacer algo si el checkbox ha sido deseleccionado
            alert("El checkbox con valor " + $(this).val() + " ha sido deseleccionado");
        }
      });
  }); {% endcomment %}
  {% comment %} let count;
    $('input').click(function (e) { 
        e.preventDefault();
        
/*         let parentSel = $(this).prev();
        parentSel.append(parentSel.clone()).;*/

        console.log('parentSel', $(this)); 

        let prevSel = $(this).prev();
        let id = parseInt(prevSel.attr("id"))+1;
        let prevClone = prevSel.clone()
        prevClone.attr("id", id );
        
        prevSel.after(prevClone);
        console.log('prevSel', prevSel); 
        console.log('parentSel', id); 
        $('#'+prevClone.attr('id')+' label').text('Tema ' + id);
        count++
  }); {% endcomment %}
  </script>
{% endblock javascripts %}